src/app/donate/page.tsx, src/app/events/page.tsx, src/app/layout.tsx, src/app/members/page.tsx, src/app/page.tsx, src/app/partners/page.tsx, src/app/teams/page.tsx
Closes #1
- Using the front page navigation and footer as default navigation and footer for every page.
=> feat: restructure layout with one universal header and footer

src/app/(home)/hero.tsx, src/app/(home)/page.tsx, src/app/events/page.tsx, src/app/layout.tsx, src/app/partners/page.tsx, src/components/atoms/nav-bar.tsx
- Match style on creator program section
- Footer group
- Add filter on partner and event page
=> feat: add team and event filter

src/app/[username]/page.tsx
Here the issues: https://github.com/KhmerCoders/khmercoders-web/issues/17
=> Issues: display wrong ordering experiences

src/app/profile/insight/page.tsx
Hope it doesn't break in the different browser
=> [Fixed]: #16 AreaChart cuts off

package-lock.json, package.json, src/utils/example.test.ts
Adding the vitest recommend by @thormengkheang along with one simple example.
```
npm run test
```
=> feat: add vitest and an example

db/main/seed.sql, src/app/[username]/page.tsx, src/app/dev_only/login/route.ts, src/app/layout.tsx, src/components/devtool.tsx, src/utils/auth.ts
Add devtools to switch between test users for login. This allows developers to contribute without needing GitHub test credentials.
=> feat: add devtools on the right bottom side and switch login tool

src/app/profile/setup/page.tsx, src/app/profile/storage/page.tsx, src/components/user-upload/context.tsx, src/components/user-upload/index.tsx, src/utils/icons.tsx
=> feat: add file manager page

drizzle/20250627030358_quiet_war_machine.sql, drizzle/meta/20250627030358_snapshot.json, drizzle/meta/_journal.json, src/actions/file.ts, src/actions/users.ts, src/app/api/upload/profile/route.ts, src/app/profile/setup/page.tsx, src/app/profile/storage/page.tsx, src/components/atoms/user-avatar.tsx, src/libs/db/schema.ts, src/services/upload.tsx, src/types/index.ts, src/utils/content-type.ts
Add dedicated personal storage page and dedicated menu
=> feat: add personal storage page

src/actions/track.ts, src/app/[username]/articles/[articleId]/[[...slug]]/page.tsx, src/app/[username]/tracker.tsx
This will record the article view in our worker-based analytics engine. We'll aggregate and precompute the data later — for now, the important part is ensuring it's being tracked.
=> feat: tracking article view

src/app/[username]/page.tsx, src/app/community/chat-metrics-chart.tsx, src/app/community/user-leaderboard.tsx, src/app/donate/page.tsx, src/app/events/page.tsx, src/app/layout.tsx, src/app/members/page.tsx, src/app/partners/page.tsx, src/app/profile/setup/alias/page.tsx, src/app/teams/page.tsx, src/components/atoms/nav-bar.tsx, src/components/atoms/partner-card.tsx, src/components/generated/button.tsx, src/components/markdown-editor/index.tsx, src/components/mode-toggle.tsx, src/components/profile-header.tsx, src/components/theme-provider.tsx, src/components/user-card.tsx, src/components/user-level-badge.tsx
- Add mode toggle
- Change CSS every pages to support both mode
=> feat: add light mode

package-lock.json, package.json, src/app/layout.tsx, src/app/profile/articles/[articleId]/page-client.tsx, src/app/profile/articles/create/page.tsx, src/components/atoms/user-avatar.tsx
This pull request introduces the `next-navigation-guard` library to enhance navigation handling across the application, particularly for unsaved changes in article editing workflows. It replaces custom navigation guard logic with the library's built-in functionality and updates related components accordingly.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R73): Added `next-navigation-guard` dependency to manage navigation guards.
* [`src/app/layout.tsx`](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed44cde2f5b3R6): Integrated `NavigationGuardProvider` into the root layout to provide navigation guard functionality across the application. [[1]](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed4 …
=> fix: unsaved change prompt

src/app/[username]/articles/[articleId]/[[...slug]]/page.tsx
Closes #65
- Remove aspect ratio and use object-cover
-
-
=> [#65]: Featured Image should not resize

src/app/community/user-leaderboard.tsx, src/libs/db/chatbot.ts, src/types/index.ts
Closes #52
- Display the linked account in the leaderboard
=> Display linked account in leaderboard

package-lock.json, package.json, src/app/dev_only/d1/browser.tsx, src/app/dev_only/d1/page.tsx, src/app/dev_only/d1/query/route.ts, src/components/devtool.tsx
Closes #{issue key}
- Add D1 database integration and update devtool for database navigation
=> Add D1 database integration and update devtool for database navigation

.prettierrc, src/app/layout.tsx, src/components/atoms/header.tsx, src/components/atoms/nav-bar.tsx, src/components/footer.tsx
Closes #75
- Highlight active link on navbar
- Enhance footer layout
=> feat: highlight active link on navbar

src/app/profile/link-account/page.tsx
Update expiration message logic to display 'Expired' badge when link code is no longer valid
Before:
After:
=> Add expired badge when code no longer valid

db/main/seed-article.sql, drizzle/20250714164912_daily_quicksilver.sql, drizzle/meta/20250714164912_snapshot.json, drizzle/meta/_journal.json, package.json, scripts/setup.js, src/app/[username]/articles/[articleId]/[[...slug]]/page.tsx, src/app/globals.css, src/components/MarkdownContent.tsx, src/components/article-item.tsx, src/components/blocks/post/CommentEditor.tsx, src/components/blocks/post/CommentItem.tsx, src/components/blocks/post/CommentList.tsx, src/components/blocks/post/CommentWidget.tsx, src/components/blocks/post/PostEditor.tsx, src/components/blocks/post/PostList.tsx, src/components/interaction-button.tsx, src/components/markdown-editor/simple-markdown.tsx, src/components/user-card.tsx, src/libs/db/schema.ts, src/server/actions/article.ts, src/server/actions/post.ts, src/server/generate-id.tsx, src/types/index.ts
=> Article comment

.copilot-instructions.md, drizzle/20250718004523_flimsy_purifiers.sql, drizzle/meta/20250718004523_snapshot.json, drizzle/meta/_journal.json, src/app/[username]/articles/[articleId]/[[...slug]]/page.tsx, src/app/[username]/moderator-tool.tsx, src/app/[username]/page.tsx, src/components/profile-header.tsx, src/components/ui/FollowerButton.tsx, src/components/user-card.tsx, src/libs/db/schema.ts, src/server/actions/follower.ts, src/server/services/followers.ts, src/types/index.ts, src/utils/auth.ts
=> Following system

src/app/profile/link-account/page.tsx
Related #92 
**Before:**
**After:**
=> Docs: Clarify Telegram‑linking instructions with bot handle & regen note

.github/workflows/check.yml, .vscode/settings.json, src/app/[username]/articles/[articleId]/[[...slug]]/page.tsx, src/app/[username]/articles/page.tsx, src/components/interaction-button.tsx, src/components/profile-header.tsx, src/components/ui/FollowerButton.tsx
Reverts KhmerCoders/khmercoders-web#106
=> Revert "Fix Follow Button State Inconsistency and Real-time Updates"

src/components/blocks/post/FeedItem.tsx, src/data/events.ts
=> fix: minor english fixes

src/app/profile/articles/components/ArticleEditor.tsx, src/app/profile/articles/components/ArticleEditorHeader.tsx, src/app/profile/articles/create/page.tsx, src/components/blocks/post/FeedItem.tsx
Closes #111 
#112 
- truncates overflow and line clamp 4 lines
- character limit on summary field makes article unable to publish with exceeded
=> fix: truncate overflow + character limit

src/app/profile/articles/[articleId]/page-client.tsx, src/server/services/feed.ts
Fixes article editing
- fixes bug introduced by [053eb01b5ff5d40713dab77a3bed8285572dbdc2](https://github.com/KhmerCoders/khmercoders-web/commit/053eb01b5ff5d40713dab77a3bed8285572dbdc2)
=> fix: fixes edit page
